from __future__ import annotations

from datetime import UTC, datetime

from backend.models.blockchain import BlockchainRecord
from backend.models.video import Video
from backend.services.similarity import SimilarityResult


class DMCAGenerator:
    def generate_notice(
        self,
        original_video: Video,
        suspect_video: Video,
        blockchain_record: BlockchainRecord,
        similarity_result: SimilarityResult,
    ) -> str:
        timestamp = datetime.now(UTC).replace(tzinfo=None).isoformat()
        match_summary = ", ".join(
            f"{match.original_timestamp:.1f}s->{match.suspect_timestamp:.1f}s ({match.similarity:.2f})"
            for match in similarity_result.matched_frames[:5]
        )

        return f"""Subject: Takedown Notice for Unauthorized Redistribution of Sports Media

Date: {timestamp}
Rights Holder: {original_video.owner}
Contact: {original_video.owner_contact or 'compliance@sportstrace.ai'}
Original Asset: {original_video.title}
Suspected Infringing Asset: {suspect_video.title}

This notice asserts ownership over the referenced sports media asset and requests removal of the suspected unauthorized redistribution identified by SportsTrace AI.

Evidence Summary:
- Similarity score: {similarity_result.score:.2f}
- Classification: {similarity_result.classification}
- Confidence: {similarity_result.confidence:.2f}
- Matching frame evidence: {match_summary}
- Ownership proof chain hash: {blockchain_record.chain_hash}
- Ownership recorded timestamp: {blockchain_record.timestamp.isoformat()}

The copyrighted work was fingerprinted using perceptual hashing with crop-resistant and edge-based features. The suspect file contains materially similar visual content to the protected source.

I have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law. The information in this notice is accurate, and under penalty of perjury, I am authorized to act on behalf of the owner.

Signed,
{original_video.owner}
Generated by SportsTrace AI
"""
